### ISSUE TITLE
make:service from sub-dir creates new service in that directory

### ISSUE THREAD

**Issue by jyecusch** [nitrictech/legacy-cli#109]
When using the `nitric make:service` command from a subdirectory of a project the nitric.yaml file is updated correctly, however, the new service is created in the subdirectory location.

#### nitric.yaml

```yaml
name: example
services:
  firstfunc:
    path: firstfunc
    runtime: function/nodets12
```

#### Project structure

```txt
project/
|
+--firstfunc/
+--nitric.yaml
```

#### nitric.yaml

```yaml
name: example
services:
  firstfunc:
    path: firstfunc
    runtime: function/nodets12
  newfunc:
    path: newfunc
    runtime: function/nodets12
```

#### Project structure

```txt
project/
|
+--firstfunc/
   |
   +--newfunc/
+--nitric.yaml
```
