### ISSUE TITLE
Add ability to set profiles per service in stack definiton

### ISSUE THREAD

**Issue by davemooreuws** [nitrictech/legacy-cli#150]
Add the ability to set options like `env` and `ports` as a profile per service.

```
name: node-project
services:
  user:
    path: user
    runtime: function/nodets12
    profile:
      dev:
        env:
          - ENV='development'
          - NODE_OPTIONS='--inspect-brk'
        ports:
          - 9229
      prod:
        env:
          - ENV='production'
```

Command:
`nitric run --profile dev`

┆Issue is synchronized with this [Jira Story](https://team-1603662928229.atlassian.net/browse/CST-9) by [Unito](https://www.unito.io)
