### ISSUE TITLE
Ability to lock versions for stacks and functions

### ISSUE THREAD

**Issue by davemooreuws** [nitrictech/legacy-cli#194]
Ability to lock versions for stacks and functions.

Should include validation of semver

```yaml
name: my-stack

version: 0.12.0-rc.15

# Nitric functions
functions:
  create:
    handler: functions/create.ts
    version: 0.12.0-rc.10
  read:
    handler: functions/read.ts
  list:
    handler: functions/list.ts
# Nitric collections
collections:
  examples: {}
# Nitric APIs
apis:
  examples: api.yaml

```
