### ISSUE TITLE
Static sites - rename buildScripts to scripts

### ISSUE THREAD

**Issue by davemooreuws** [nitrictech/legacy-cli#211]
Currently if you are running or deploying a static site using Node and haven't installed your modules you will get errors. 

I suggest we rename **buildScripts** to **scripts** so users can add their yarn install or npm ci in here. The name change should remove any confusion. Part of this change will be refactoring documentation.

```yaml
sites:
  example-site:
    path: .
    assetPath: ./build
    scripts:
      - yarn install --frozen-lockfile
      - yarn build
```
