### ISSUE TITLE
do tree shaking as part of container build (feature request)

### ISSUE THREAD

**Issue by shaf-h** [nitrictech/legacy-cli#250]
Some of my functions use pretty big modules (e.g. puppeteer, pdf gen, image manipulation). It would be useful to exclude them from the function containers that don't need them.

**Comment by asalkeld** [comment]
you can currently use "excludes" to remove files from the build.
```
functions:
  create:
    handler: functions/create.ts
    excludes:
      - afile
      - anotherflie
```
Does this help or are you wanting some other behaviour?
